# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopherdoc < Formula
  desc "Improved go doc with terminal syntax highlighting"
  homepage "https://github.com/ravener/gopherdoc"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ravener/gopherdoc/releases/download/v1.0.0/gopherdoc_1.0.0_darwin_x86_64.tar.gz"
    sha256 "671e036b8a26c583a2ea514fa1dd87c18661ee5b4eca643f80f56280258f3f62"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ravener/gopherdoc/releases/download/v1.0.0/gopherdoc_1.0.0_darwin_arm64.tar.gz"
    sha256 "52ade8ae66d8a46e123982836697dc46f98b7b251d0153a0a8e6cad0f6b70721"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ravener/gopherdoc/releases/download/v1.0.0/gopherdoc_1.0.0_linux_x86_64.tar.gz"
    sha256 "6650665c7691364d97988dc12f3428db9a3cbbe4831d2fbad61577347bd9f3de"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ravener/gopherdoc/releases/download/v1.0.0/gopherdoc_1.0.0_linux_armv6.tar.gz"
    sha256 "f85f6107fc8f918e2a5899951f3131c62ab5a98080d0eb13abc54078216e2a32"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ravener/gopherdoc/releases/download/v1.0.0/gopherdoc_1.0.0_linux_arm64.tar.gz"
    sha256 "b58500e2594c776990241bcad8192cf13d6f9aa7302b126e8a7e7a3d7a710996"
  end

  def install
    bin.install "gopherdoc"
  end
end
