# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ImgApi < Formula
  desc "An image server api for generating memes for Discord Bots."
  homepage "https://github.com/ravener/img-api"
  version "1.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ravener/img-api/releases/download/v1.2.5/img-api_1.2.5_Darwin_arm64.tar.gz"
      sha256 "6689208971c31dbf0d4ae962ba8068c713dd88d2c20328c7874509a946447431"

      def install
        bin.install_symlink "img-api"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ravener/img-api/releases/download/v1.2.5/img-api_1.2.5_Darwin_x86_64.tar.gz"
      sha256 "10ac56471463cff453b071f0e3d1d75d61b70476cfce86e054e7dcc9ec932286"

      def install
        bin.install_symlink "img-api"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ravener/img-api/releases/download/v1.2.5/img-api_1.2.5_Linux_armv6.tar.gz"
      sha256 "85197230d4b5e482620598c57c985d76e9ec92a16159dd462df76675dec40371"

      def install
        bin.install_symlink "img-api"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ravener/img-api/releases/download/v1.2.5/img-api_1.2.5_Linux_arm64.tar.gz"
      sha256 "44d1841f91dd697616c3678303f394d3f2dafd926c376b955cecbfbdeb6c767f"

      def install
        bin.install_symlink "img-api"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ravener/img-api/releases/download/v1.2.5/img-api_1.2.5_Linux_x86_64.tar.gz"
      sha256 "2a2a79c8288c2ebf21e8205cc5e4477992fdf5a3df46571ca225174731751cf8"

      def install
        bin.install_symlink "img-api"
      end
    end
  end
end
