# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lxym < Formula
  desc "CLI tool to browse learnxinyminutes.com pages in your terminal"
  homepage "https://github.com/ravener/lxym"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ravener/lxym/releases/download/v1.0.0/lxym_1.0.0_darwin_x86_64.tar.gz"
    sha256 "fbcb50686726f3f0c95bee37c9c1fa717d5817773fe0f4e53c8db15f2ad370ac"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ravener/lxym/releases/download/v1.0.0/lxym_1.0.0_darwin_arm64.tar.gz"
    sha256 "07ff340c040840271b536602971f547252e25afb301fdce7f8888bf03601a9fa"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ravener/lxym/releases/download/v1.0.0/lxym_1.0.0_linux_x86_64.tar.gz"
    sha256 "258a084bb15b47bc2e5c08d2af38fad13da6559cec2a8cc200b21c1cc87b53e3"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ravener/lxym/releases/download/v1.0.0/lxym_1.0.0_linux_armv6.tar.gz"
    sha256 "4f414de9a7d197993a51ee3f5bb61ba45a890a8de25863a42c7c9a3241bd9718"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ravener/lxym/releases/download/v1.0.0/lxym_1.0.0_linux_arm64.tar.gz"
    sha256 "ef57897305a743041fea434c189be829010e221b28a240b1d588ea59ebb432a4"
  end

  depends_on "less"

  def install
    bin.install "lxym"
  end
end
